[MusicDots]
Meter=Shape
DynamicVariables=1
UpdateDivider=#FreezeVisualizerMeters#
Shape=Ellipse ((#Radius#+([MeasureBand0]*#JumpHeight#))*cos(rad(#degree0#))+#CentreX#),((#Radius#+([MeasureBand0]*#JumpHeight#))*sin(rad(#degree0#))+#CentreY#),#DotRadius#|Stroke Color #Color1#Shape1=Ellipse ((300+([MeasureBand0]*100))*cos(rad(#degree0#))+450),((300+([MeasureBand0]*100))*sin(rad(#degree0#))+450),3|StrokeWidth 0|Fill Color 255,255,255
Shape2=Ellipse ((300+([MeasureBand1]*100))*cos(rad(#degree1#))+450),((300+([MeasureBand1]*100))*sin(rad(#degree1#))+450),3|StrokeWidth 0|Fill Color 255,255,255
Shape3=Ellipse ((300+([MeasureBand2]*100))*cos(rad(#degree2#))+450),((300+([MeasureBand2]*100))*sin(rad(#degree2#))+450),3|StrokeWidth 0|Fill Color 255,255,255
Shape4=Ellipse ((300+([MeasureBand3]*100))*cos(rad(#degree3#))+450),((300+([MeasureBand3]*100))*sin(rad(#degree3#))+450),3|StrokeWidth 0|Fill Color 255,255,255
Shape5=Ellipse ((300+([MeasureBand4]*100))*cos(rad(#degree4#))+450),((300+([MeasureBand4]*100))*sin(rad(#degree4#))+450),3|StrokeWidth 0|Fill Color 255,255,255
Shape6=Ellipse ((300+([MeasureBand5]*100))*cos(rad(#degree5#))+450),((300+([MeasureBand5]*100))*sin(rad(#degree5#))+450),3|StrokeWidth 0|Fill Color 255,255,255
Shape7=Ellipse ((300+([MeasureBand6]*100))*cos(rad(#degree6#))+450),((300+([MeasureBand6]*100))*sin(rad(#degree6#))+450),3|StrokeWidth 0|Fill Color 255,255,255
Shape8=Ellipse ((300+([MeasureBand7]*100))*cos(rad(#degree7#))+450),((300+([MeasureBand7]*100))*sin(rad(#degree7#))+450),3|StrokeWidth 0|Fill Color 255,255,255
Shape9=Ellipse ((300+([MeasureBand8]*100))*cos(rad(#degree8#))+450),((300+([MeasureBand8]*100))*sin(rad(#degree8#))+450),3|StrokeWidth 0|Fill Color 255,255,255
Shape10=Ellipse ((300+([MeasureBand9]*100))*cos(rad(#degree9#))+450),((300+([MeasureBand9]*100))*sin(rad(#degree9#))+450),3|StrokeWidth 0|Fill Color 255,255,255
Shape11=Ellipse ((300+([MeasureBand10]*100))*cos(rad(#degree10#))+450),((300+([MeasureBand10]*100))*sin(rad(#degree10#))+450),3|StrokeWidth 0|Fill Color 255,255,255
Shape12=Ellipse ((300+([MeasureBand11]*100))*cos(rad(#degree11#))+450),((300+([MeasureBand11]*100))*sin(rad(#degree11#))+450),3|StrokeWidth 0|Fill Color 255,255,255
Shape13=Ellipse ((300+([MeasureBand12]*100))*cos(rad(#degree12#))+450),((300+([MeasureBand12]*100))*sin(rad(#degree12#))+450),3|StrokeWidth 0|Fill Color 255,255,255
Shape14=Ellipse ((300+([MeasureBand13]*100))*cos(rad(#degree13#))+450),((300+([MeasureBand13]*100))*sin(rad(#degree13#))+450),3|StrokeWidth 0|Fill Color 255,255,255
Shape15=Ellipse ((300+([MeasureBand14]*100))*cos(rad(#degree14#))+450),((300+([MeasureBand14]*100))*sin(rad(#degree14#))+450),3|StrokeWidth 0|Fill Color 255,255,255
Shape16=Ellipse ((300+([MeasureBand15]*100))*cos(rad(#degree15#))+450),((300+([MeasureBand15]*100))*sin(rad(#degree15#))+450),3|StrokeWidth 0|Fill Color 255,255,255
Shape17=Ellipse ((300+([MeasureBand16]*100))*cos(rad(#degree16#))+450),((300+([MeasureBand16]*100))*sin(rad(#degree16#))+450),3|StrokeWidth 0|Fill Color 255,255,255
Shape18=Ellipse ((300+([MeasureBand17]*100))*cos(rad(#degree17#))+450),((300+([MeasureBand17]*100))*sin(rad(#degree17#))+450),3|StrokeWidth 0|Fill Color 255,255,255
Shape19=Ellipse ((300+([MeasureBand18]*100))*cos(rad(#degree18#))+450),((300+([MeasureBand18]*100))*sin(rad(#degree18#))+450),3|StrokeWidth 0|Fill Color 255,255,255
Shape20=Ellipse ((300+([MeasureBand19]*100))*cos(rad(#degree19#))+450),((300+([MeasureBand19]*100))*sin(rad(#degree19#))+450),3|StrokeWidth 0|Fill Color 255,255,255
Shape21=Ellipse ((300+([MeasureBand20]*100))*cos(rad(#degree20#))+450),((300+([MeasureBand20]*100))*sin(rad(#degree20#))+450),3|StrokeWidth 0|Fill Color 255,255,255
Shape22=Ellipse ((300+([MeasureBand21]*100))*cos(rad(#degree21#))+450),((300+([MeasureBand21]*100))*sin(rad(#degree21#))+450),3|StrokeWidth 0|Fill Color 255,255,255
Shape23=Ellipse ((300+([MeasureBand22]*100))*cos(rad(#degree22#))+450),((300+([MeasureBand22]*100))*sin(rad(#degree22#))+450),3|StrokeWidth 0|Fill Color 255,255,255
Shape24=Ellipse ((300+([MeasureBand23]*100))*cos(rad(#degree23#))+450),((300+([MeasureBand23]*100))*sin(rad(#degree23#))+450),3|StrokeWidth 0|Fill Color 255,255,255